addons:
- name: aws-ebs-csi-driver
  wellKnownPolicies:
    ebsCSIController: true
apiVersion: eksctl.io/v1alpha5
iam:
  withOIDC: true
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2023
  desiredCapacity: 4
  iam:
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    - arn:aws:iam::755182613526:policy/hopsworks-clusterlex-policy
    - null
    withAddonPolicies:
      awsLoadBalancerController: true
  instanceType: m6i.2xlarge
  maxSize: 4
  minSize: 1
  name: ng-1
  ssh:
    allow: true
  volumeSize: 100
metadata:
  name: clustercluster
  region: eu-west-2
  version: '1.29'
