apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
