global:
  _hopsworks:
    imagePullPolicy: IfNotPresent
    minio:
      enabled: true
    externalLoadBalancers:
      enabled: false
    managedDockerRegistery:
      enabled: false
    security:
      tls:
        enabled: false
    cloudProvider: ""

hopsworks:
  enabled: true
  replicaCount:
    worker: 1
  resources:
    admin:
      auto_jvm: true
      jvm:
        memory:
          heap: 256
          metaspace: 128
          compressedClassSpaceSize: 64
          nonMethodCodeHeapSize: 5
          profiledCodeHeapSize: 32
          nonProfiledCodeHeapSize: 32
          buffer: 64
    worker:
      auto_jvm: true
      jvm:
        memory:
          heap: 512
          metaspace: 128
          compressedClassSpaceSize: 64
          nonMethodCodeHeapSize: 5
          profiledCodeHeapSize: 32
          nonProfiledCodeHeapSize: 32
          buffer: 128
  service:
    type: NodePort

rondb:
  isMultiNodeCluster: false
  clusterSize:
    activeDataReplicas: 1
    numNodeGroups: 1
    minNumMySQLServers: 1
    maxNumMySQLServers: 1
    minNumRdrs: 1
    maxNumRdrs: 1
  resources:
    limits:
      cpus:
        mgmds: 0.1
        ndbmtds: 0.2
        mysqlds: 0.2
        rdrs: 0.1
      memory:
        ndbmtdsMiB: 256
        mysqldMiB: 256
        rdrsMiB: 128
    requests:
      cpus:
        mgmds: 0.05
        mysqlds: 0.1
        rdrs: 0.05
      memory:
        ndbmtdsMiB: 128
        mysqldMiB: 128
        rdrsMiB: 64

minio:
  replicas: 1
  persistence:
    size: 1Gi
  resources:
    limits:
      cpu: "0.2"
      memory: "256Mi"
    requests:
      cpu: "0.1"
      memory: "128Mi"

consul:
  enabled: true
  server:
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  client:
    enabled: false

# Disabled components
airflow:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
kserve:
  enabled: false
logstash:
  enabled: false
opensearch:
  enabled: false
onlinefs:
  enabled: false
spark:
  enabled: false
docker-registry:
  enabled: false
olk:
  enabled: false
hopsfs:
  enabled: false
kafka:
  enabled: false
arrowflight:
  enabled: false
istio:
  enabled: false
knative:
  enabled: false

# Global resource limits for any component not specifically configured
resourceLimits: &resourceLimits
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Apply global resource limits to other components
cert-manager:
  resources: *resourceLimits

filebeat:
  resources: *resourceLimits

# Drastically reduce CA resources
hopsworks-ca:
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Reduce admin resources
hopsworks-admin:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi