global:
  _hopsworks:
    imagePullPolicy: Never
    image:
      registry: ""
      repository: custom-hopsworks
      tag: arm64
    minio:
      enabled: false
    managedDockerRegistery:
      enabled: false
    externalLoadBalancers:
      enabled: false

hopsfs:
  enabled: false

rondb:
  enabled: false

kafka:
  enabled: false

consul:
  enabled: false

docker-registry:
  enabled: false

airflow:
  enabled: false

ingress:
  enabled: true
  ingressClassName: traefik

onlinefs:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

nvidiadci:
  enabled: false

kube-kserve:
  enabled: false

olk:
  enabled: false